version: '3.9'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      WELLIO_DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/wellio
      WELLIO_REDIS_URL: redis://redis:6379/0
      WELLIO_SECRET_KEY: dev-secret
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wellio
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
